name: Deploy Angular + folders.json to GitHub Pages

on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '20'

      - name: Install dependencies
        run: npm install
        working-directory: aplicacion

      - name: Generate folders.json
        run: node generate-folders.js
        working-directory: aplicacion

      - name: Build Angular app
        run: npm run build -- --output-path=docs
        working-directory: aplicacion

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3.9.3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./aplicacion/docs
