name: Deploy Angular

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v5.0.0

      - name: Setup Node.js environment
        uses: actions/setup-node@v3.9.1
        with:
          node-version: '20'

      - name: Install dependencies
        run: npm install
        working-directory: application

      - name: Generate folders.json
        run: node generate-folders.js
        working-directory: application

      - name: Build Angular app
        run: npm run build:prod
        working-directory: application

      - name: Deploy to pages
        uses: crazy-max/ghaction-github-pages@v4.2.0
        with:
          build_dir: application/dist/angular-docs
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
